Repository auditdbio/audit-web, pull requests merged in 2022-12, with the labels that each got.

#3 Implement user account page
  src/App.scss
  src/App.tsx
  src/animations/main.router.tsx
  src/app.store.ts
  src/auth/cabinet/Cabinet.tsx
  src/auth/registration/Registation.tsx
  src/auth/registration/Registration.scss
  src/auth/state/auth.epic.ts
  src/auth/state/auth.reducer.ts
  src/auth/state/auth.selectors.ts
  src/shared/components/user-contol/UserControl.tsx
  src/shared/containers/app-header/AppHeader.tsx
  src/shared/guards/AuthGuard.tsx
  src/shared/guards/UnAuthGuard.tsx
  src/shared/state/shared.epics.ts
  src/shared/state/shared.reducer.ts
  src/shared/state/shared.selectors.ts
  src/user/api/user.api.ts
  src/user/cabinet/Cabinet.tsx
  src/user/helpers/LoginDataCheck.ts
  src/user/helpers/RegistrationDataCheck.ts
  src/user/login/Login.scss
  src/user/login/Login.tsx
  src/user/registration/Registation.tsx
  src/user/registration/Registration.scss
  src/user/state/user.epic.ts
  src/user/state/user.reducer.ts
  src/user/state/user.selectors.ts
Labels: feature, Web

#22 [#19] Remove JWT token on user logout
  src/shared/components/user-contol/UserControl.tsx
  src/user/api/user.api.ts
  src/user/state/user.epic.ts
  src/user/state/user.reducer.ts
Labels: feature, Web

#17 User page
  src/App.scss
  src/index.css
  src/shared/components/user-navigate/UserNavigate.tsx
  src/user/cabinet/Cabinet.scss
  src/user/cabinet/Cabinet.tsx
Labels: refactoring, Web

#25 [#23] Pull common styles in to mixins
  src/styles/_colors.scss
  src/styles/_mixins.scss
  src/styles/_sizes.scss
  src/styles/mixins/avatar.scss
  src/styles/mixins/page-button.scss
  src/styles/mixins/page-panel.scss
  src/styles/mixins/page-title.scss
  src/styles/styles.scss
  src/user/cabinet/Cabinet.scss
  src/user/cabinet/Cabinet.tsx
Labels: refactoring, Web

#18 [#15] Adjust Sign In page design
  src/styles/_mixins.scss
  src/styles/mixins/input.scss
  src/styles/mixins/page-input-label.scss
  src/styles/mixins/page-input.scss
  src/user/login/Login.scss
  src/user/login/Login.tsx
Labels: refactoring, Web

#29 Refactoring and renaming of cabinet component
  src/App.tsx
  src/animations/main.router.tsx
  src/shared/components/user-contol/UserControl.tsx
  src/shared/guards/UnAuthGuard.tsx
  src/styles/mixins/page-input.scss
  src/user/containers/login/Login.scss
  src/user/containers/login/Login.tsx
  src/user/containers/profile/Profile.scss
  src/user/containers/profile/Profile.tsx
  src/user/containers/registration/Registation.tsx
  src/user/containers/registration/Registration.scss
Labels: refactoring

#35 [#30] Customer component
  src/@customer/containers/customer/Customer.scss
  src/@customer/containers/customer/Customer.tsx
  src/@customer/models/customer.ts
  src/@customer/state/customer.reducer.ts
Labels: Web

#39 Implement registration type swithes
  src/user/containers/registration/Registation.tsx
  src/user/containers/registration/Registration.scss
Labels: refactoring

#44 Feature/27
  src/@auditor/api/auditor.adaptor.ts
  src/@auditor/api/auditor.api.ts
  src/@auditor/components/auditor-page/AuditorPage.scss
  src/@auditor/components/auditor-page/AuditorPage.tsx
  src/@auditor/containers/auditor-panel/AuditorPanel.scss
  src/@auditor/containers/auditor-panel/AuditorPanel.tsx
  src/@auditor/models/auditor.ts
  src/@auditor/state/auditor.epics.ts
  src/@auditor/state/auditor.reducer.ts
  src/@auditor/state/auditor.selectors.ts
  src/@customer/api/customer.api.ts
  src/@customer/state/customer.reducer.ts
  src/App.tsx
  src/app.store.ts
  src/auditors/state/auditors.epics.ts
  src/auditors/state/auditors.reducer.ts
  src/user/api/user.adaptor.ts
  src/user/api/user.api.ts
  src/user/state/user.reducer.ts
Labels: feature, Web

#50 Feature/31
  src/@auditor/components/auditor-panel/AuditorPanel.scss
  src/@auditor/components/auditor-panel/AuditorPanel.tsx
  src/@auditor/containers/auditor-page/AuditorPage.scss
  src/@auditor/containers/auditor-page/AuditorPage.tsx
  src/@customer/api/project.adaptor.ts
  src/@customer/api/project.api.ts
  src/@customer/components/customer-panel/CustomerPanel.scss
  src/@customer/components/customer-panel/CustomerPanel.tsx
  src/@customer/components/project-card/ProjectCard.scss
  src/@customer/components/project-card/ProjectCard.tsx
  src/@customer/components/projects-panel/ProjectsPanel.scss
  src/@customer/components/projects-panel/ProjectsPanel.tsx
  src/@customer/containers/customer-page/CustomerPage.scss
  src/@customer/containers/customer-page/CustomerPage.tsx
  src/@customer/containers/project-page/ProjectPage.scss
  src/@customer/containers/project-page/ProjectPage.tsx
  src/@customer/models/project.ts
  src/@customer/state/customer.epics.ts
  src/@customer/state/customer.reducer.ts
  src/@customer/state/customer.selectors.ts
  src/App.tsx
  src/shared/containers/app-header/AppHeader.tsx
  src/shared/guards/AuthGuard.tsx
  src/shared/guards/UnAuthGuard.tsx
  src/shared/state/shared.epics.ts
  src/styles/mixins/page-button.scss
  src/styles/mixins/page-panel.scss
  src/user/api/user.api.ts
  src/user/containers/login/Login.tsx
  src/user/containers/profile/Profile.tsx
  src/user/containers/registration/Registation.tsx
  src/user/helpers/RegistrationDataCheck.ts
Labels: feature, Web

#59 [#55] Add publish project button
  public/images/avatar/1.jpg
  public/images/avatar/10.jpg
  public/images/avatar/2.jpg
  public/images/avatar/3.jpg
  public/images/avatar/4.jpg
  public/images/avatar/5.jpg
  public/images/avatar/7.jpg
  public/images/avatar/8.jpg
  public/images/avatar/9.jpg
  src/@auditor/components/auditor-card/AuditorCard.scss
  src/@auditor/components/auditor-card/AuditorCard.tsx
  src/@customer/components/project-card/ProjectCard.scss
  src/@customer/components/project-card/ProjectCard.tsx
  src/@customer/containers/project-page/ProjectPage.scss
  src/@customer/containers/project-page/ProjectPage.tsx
  src/app.constants.ts
  src/shared/components/user-contol/UserControl.tsx
  src/shared/containers/main/MainPage.tsx
  src/styles/_mixins.scss
  src/styles/_sizes.scss
  src/styles/mixins/page-button.scss
  src/styles/mixins/size.scss
  src/user/containers/profile/Profile.tsx
Labels: feature, Web

#62 [#60] Move tegs to the component
  src/@auditor/components/auditor-card/AuditorCard.scss
  src/@auditor/containers/auditor-info/AuditorInfo.tsx
  src/@customer/components/customer-info/ProjectInfo.tsx
  src/@customer/components/project-card/ProjectCard.scss
  src/shared/components/tags/Tags.scss
  src/shared/components/tags/Tags.tsx
Labels: refactoring, Web
