Repository auditdbio/audit-web, pull requests merged in 2023-01, with the labels that each got.

#64 [#63] Status bar implement
  src/@customer/components/project-card/ProjectCard.tsx
  src/@customer/components/projects-panel/ProjectsPanel.tsx
  src/shared/components/status-bar/StatusBar.scss
  src/shared/components/status-bar/StatusBar.tsx
Labels: feature, Web

#67 [#14] Adjust main page design
  package.json
  src/@auditor/components/auditor-card/AuditorCard.scss
  src/@auditor/components/auditor-card/AuditorCard.tsx
  src/@auditor/containers/auditor-page/AuditorPage.tsx
  src/@customer/components/project-card/ProjectCard.scss
  src/@customer/components/project-card/ProjectCard.tsx
  src/@customer/containers/customer-page/CustomerPage.tsx
  src/@customer/containers/project-page/ProjectPage.scss
  src/@customer/containers/project-page/ProjectPage.tsx
  src/index.tsx
  src/shared/components/user-contol/UserControl.tsx
  src/shared/components/welcome/Welcome.scss
  src/shared/components/welcome/Welcome.tsx
  src/shared/containers/app-header/AppHeader.scss
  src/shared/containers/main/MainPage.scss
  src/shared/containers/main/MainPage.tsx
  src/styles/styles.scss
  src/theme.ts
  src/user/containers/login/Login.tsx
  src/user/containers/profile/Profile.tsx
  src/user/containers/registration/Registation.tsx
  yarn.lock
Labels: Web

#72 Feature/66
  src/@auditor/components/auditor-card/AuditorCard.scss
  src/@auditor/components/auditor-info/AuditorInfo.scss
  src/@auditor/components/auditor-panel/AuditorPanel.scss
  src/@customer/components/customer-info/ProjectInfo.scss
  src/@customer/components/customer-panel/CustomerPanel.scss
  src/@customer/components/project-card/ProjectCard.scss
  src/@customer/components/projects-panel/ProjectsPanel.scss
  src/@customer/containers/project-page/ProjectPage.scss
  src/assets/background-girl/Girls.scss
  src/assets/background-girl/LeftGirl.tsx
  src/assets/background-girl/RightGirl.tsx
  src/index.css
  src/shared/components/search/search.tsx
  src/shared/components/welcome/Welcome.scss
  src/shared/components/welcome/Welcome.tsx
  src/shared/containers/app-header/AppHeader.scss
  src/shared/containers/app-header/AppHeader.tsx
  src/shared/containers/main/MainPage.scss
  src/shared/containers/main/MainPage.tsx
  src/styles/_colors.scss
  src/styles/_mixins.scss
  src/styles/_sizes.scss
  src/styles/mixins/page-button.scss
  src/styles/styles.scss
  src/theme.ts
  src/types.d.ts
  src/user/containers/login/Login.scss
  src/user/containers/login/Login.tsx
  src/user/containers/profile/Profile.scss
  src/user/containers/profile/Profile.tsx
  src/user/containers/registration/Registation.tsx
  src/user/containers/registration/Registration.scss
Labels: Web

#75 [#74] Implement slider component for tax field
  src/@auditor/api/auditor.adaptor.ts
  src/@auditor/api/auditor.api.ts
  src/@auditor/components/auditor-info/AuditorInfo.tsx
  src/@auditor/components/auditor-panel/AuditorPanel.tsx
  src/@auditor/containers/auditor-page/AuditorPage.tsx
  src/shared/components/app-slider/AppSlider.scss
  src/shared/components/app-slider/AppSlider.tsx
  src/shared/components/range-slider/RangeSlider.scss
  src/shared/components/range-slider/RangeSlider.tsx
  src/shared/models/auditor.ts
Labels: feature, Web

#77 [#32] Load Audits
  package.json
  src/@auditor/containers/auditor-page/AuditorPage.scss
  src/@auditor/containers/auditor-page/AuditorPage.tsx
  src/@auditor/state/auditor.epics.ts
  src/@auditor/state/auditor.reducer.ts
  src/@auditor/state/auditor.selectors.ts
  src/@customer/containers/customer-page/CustomerPage.scss
  src/@customer/containers/customer-page/CustomerPage.tsx
  src/@customer/state/customer.epics.ts
  src/@customer/state/customer.reducer.ts
  src/app.constants.ts
  src/app.store.ts
  src/shared/api/audit.api.ts
  src/shared/components/audit-card/AuditCard.scss
  src/shared/components/audit-card/AuditCard.tsx
  src/shared/models/audit.ts
  yarn.lock
Labels: feature, Web

#81 [#79] Adjust Auditor card and different styles
  src/@auditor/api/auditor.adaptor.ts
  src/@auditor/components/auditor-card/AuditorCard.tsx
  src/@auditor/components/auditor-info/AuditorInfo.tsx
  src/@auditor/components/auditor-panel/AuditorPanel.tsx
  src/@auditor/containers/auditor-page/AuditorPage.tsx
  src/@customer/components/customer-panel/CustomerPanel.tsx
  src/@customer/components/project-info/ProjectInfo.tsx
  src/@customer/containers/project-page/ProjectPage.tsx
  src/shared/containers/main/MainPage.tsx
  src/shared/models/auditor.ts
  src/styles/mixins/page-input-label.scss
  src/theme.ts
Labels: Web

#87 [#80] Adjust Project page
  src/@auditor/components/auditor-card/AuditorCard.scss
  src/@auditor/components/auditor-info/AuditorInfo.scss
  src/@auditor/components/auditor-panel/AuditorPanel.scss
  src/@auditor/components/auditor-panel/AuditorPanel.tsx
  src/@auditor/containers/auditor-page/AuditorPage.scss
  src/@auditor/containers/auditor-page/AuditorPage.tsx
  src/@customer/api/project.adaptor.ts
  src/@customer/components/audit-accept/AuditAccept.scss
  src/@customer/components/customer-info/CustomerInfo.scss
  src/@customer/components/customer-panel/CustomerPanel.tsx
  src/@customer/components/project-card/ProjectCard.scss
  src/@customer/components/project-info/ProjectInfo.scss
  src/@customer/containers/customer-page/CustomerPage.scss
  src/@customer/containers/customer-page/CustomerPage.tsx
  src/@customer/containers/project-page/ProjectPage.scss
  src/@customer/containers/project-page/ProjectPage.tsx
  src/index.css
  src/shared/components/app-slider/AppSlider.tsx
  src/shared/components/audit-card/AuditCard.scss
  src/shared/components/header-links/HeaderLinks.scss
  src/shared/components/range-slider/RangeSlider.tsx
  src/shared/components/status-bar/StatusBar.scss
  src/shared/components/tags/Tags.scss
  src/shared/components/user-type-switch/UserTypeSwitch.scss
  src/shared/components/welcome/Welcome.scss
  src/shared/containers/app-header/AppHeader.scss
  src/shared/models/project.ts
  src/styles/_colors.scss
  src/styles/_sizes.scss
  src/styles/mixins/page-alert.scss
  src/styles/mixins/page-input-label.scss
  src/styles/mixins/page-input.scss
  src/styles/mixins/page-panel.scss
  src/styles/mixins/page-title.scss
  src/styles/styles.scss
  src/theme.ts
  src/user/containers/profile/Profile.scss
  src/user/containers/registration/Registation.tsx
  src/user/containers/registration/Registration.scss
Labels: feature, Web

#90 [#43, #69]Audit cards and audit info components implement
  src/@auditor/components/audit-card/AuditorAuditCard.scss
  src/@auditor/components/audit-card/AuditorAuditCard.tsx
  src/@auditor/components/audit-info/AuditInfo.scss
  src/@auditor/components/audit-info/AuditInfo.tsx
  src/@auditor/components/auditor-info/AuditorInfo.scss
  src/@auditor/components/auditor-panel/AuditorPanel.tsx
  src/@auditor/containers/auditor-page/AuditorPage.scss
  src/@auditor/containers/auditor-page/AuditorPage.tsx
  src/@auditor/state/auditor.epics.ts
  src/@auditor/state/auditor.reducer.ts
  src/@auditor/state/auditor.selectors.ts
  src/@customer/components/audit-card/CustomerAuditCard.scss
  src/@customer/components/audit-card/CustomerAuditCard.tsx
  src/@customer/components/customer-info/CustomerInfo.scss
  src/@customer/components/project-card/ProjectCard.scss
  src/@customer/components/project-card/ProjectCard.tsx
  src/@customer/containers/customer-page/CustomerPage.scss
  src/@customer/containers/customer-page/CustomerPage.tsx
  src/shared/components/app-slider/AppSlider.scss
  src/shared/components/audit-card/AuditCard.scss
  src/shared/components/bages/Bages.scss
  src/shared/components/bages/Bages.tsx
  src/shared/components/range-slider/RangeSlider.scss
  src/shared/containers/main/MainPage.scss
  src/shared/containers/main/MainPage.tsx
  src/shared/models/audit.ts
  src/styles/_mixins.scss
  src/styles/_sizes.scss
  src/styles/mixins/audit-card.scss
  src/user/containers/profile/Profile.tsx
  src/user/helpers/LoginDataCheck.ts
Labels: feature, Web

#93 [#88] Implement Quick Auditor Search from Project Page
  README.md
  src/@auditor/api/auditor.api.ts
  src/@auditor/components/auditor-info/AuditorInfo.scss
  src/@auditor/components/auditor-info/AuditorInfo.tsx
  src/@auditor/containers/auditor-page/AuditorPage.scss
  src/@customer/api/project.api.ts
  src/@customer/containers/project-page/ProjectPage.scss
  src/@customer/containers/project-page/ProjectPage.tsx
  src/@customer/state/customer.epics.ts
  src/@customer/state/customer.reducer.ts
  src/@customer/state/customer.selectors.ts
  src/shared/components/quick-search/QuickSearch.scss
  src/shared/components/quick-search/QuickSearch.tsx
  src/shared/containers/app-header/AppHeader.scss
  src/shared/containers/app-header/AppHeader.test.tsx
  src/shared/containers/app-header/AppHeader.tsx
  src/shared/models/auditor.ts
  src/styles/mixins/page-input.scss
  src/styles/mixins/page-title.scss
  src/theme.ts
Labels: feature, Web

#98 Main page styles
  src/@auditor/components/audit-card/AuditorAuditCard.scss
  src/@auditor/components/audit-info/AuditInfo.scss
  src/@auditor/components/auditor-card/AuditorCard.scss
  src/@auditor/components/auditor-card/AuditorCard.tsx
  src/@auditor/components/auditor-info/AuditorInfo.scss
  src/@auditor/components/auditor-info/AuditorInfo.tsx
  src/@auditor/components/auditor-panel/AuditorPanel.scss
  src/@auditor/containers/auditor-page/AuditorPage.scss
  src/@customer/components/audit-accept/AuditAccept.scss
  src/@customer/components/audit-card/CustomerAuditCard.scss
  src/@customer/components/customer-info/CustomerInfo.scss
  src/@customer/components/customer-panel/CustomerPanel.scss
  src/@customer/components/project-card/ProjectCard.scss
  src/@customer/components/project-info/ProjectInfo.scss
  src/@customer/components/projects-panel/ProjectsPanel.scss
  src/@customer/containers/customer-page/CustomerPage.scss
  src/@customer/containers/project-page/ProjectPage.scss
  src/index.css
  src/shared/components/header-links/HeaderLinks.scss
  src/shared/components/header-links/HeaderLinks.tsx
  src/shared/components/user-navigate/UserNavigate.scss
  src/shared/components/user-type-switch/UserTypeSwitch.scss
  src/shared/components/welcome/Welcome.scss
  src/shared/components/welcome/Welcome.tsx
  src/shared/containers/app-header/AppHeader.scss
  src/shared/containers/app-header/AppHeader.tsx
  src/shared/containers/main/MainPage.scss
  src/shared/containers/main/MainPage.tsx
  src/styles/_sizes.scss
  src/styles/mixins/audit-card.scss
  src/styles/mixins/page-panel.scss
  src/theme.ts
  src/user/containers/registration/Registration.scss
Labels: refactoring, Web
